name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
          flutter-version: '1.18.0-dev.5.0'
      - run: flutter config --enable-web
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release
      - run: |
          #git add .
          #git commit -m "workflow Done"
          git remote remove origin
          git remote add origin https://${{secrets.commit_secret}}@github.com/samuelrajasingh/flutter_web.git
          git checkout -b gh-pages
          git config user.name Rajasingh Samuel
          git config user.email rajasinghsamuelb@karunya.edu.in
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
